//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThatcherSongListBox___Ashi_Alfassi__Meir_Di_Capua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThatcherSongListBox___Ashi_Alfassi__Meir_Di_Capua.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream iCarly {
            get {
                return ResourceManager.GetStream("iCarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6000
        ///I know, you see
        ///8300
        ///Somehow the world will change for me
        ///10500
        ///And be so wonderful
        ///13000
        ///
        ///15100
        ///Live life, breathe air
        ///17000
        ///I know somehow we&apos;re gonna get there
        ///19650
        ///And feel so wonderful
        ///21990
        ///
        ///24000
        ///I will make you change your mind
        ///28500
        ///These things happen all the time
        ///32300
        ///And it&apos;s all real
        ///35000
        ///I&apos;m telling you just how I feel
        ///37100
        ///
        ///37100
        ///So wake up the members of my nation
        ///41000
        ///It&apos;s your time to be
        ///42700
        ///There&apos;s no chance unless you take one
        ///45750
        ///And the ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iCarlyLyrics {
            get {
                return ResourceManager.GetString("iCarlyLyrics", resourceCulture);
            }
        }
    }
}
